# Assignment

In [1]:
import numpy as np

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [2]:
mat = np.arange(25, dtype=np.int32).reshape(5, 5)
mat.fill(6)

print("#Original Matrix:")
print(mat)

new_mat = [0 if (0 not in (row, col) and (mat.shape[0]-1) not in (row, col)) else mat[row][col] \
     for row in np.arange(mat.shape[0]) for col in np.arange(mat.shape[1])]

print("\n#6 on the border and 0 inside in the array:")
print(np.array(new_mat).reshape(5, 5))
print("-" * 30)

#Original Matrix:
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]

#6 on the border and 0 inside in the array:
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]
------------------------------


In [3]:
mat = np.empty(25, dtype=np.int32).reshape(5, 5)
mat.fill(6)

print("#Original Matrix:")
print(mat)

print("\n#6 on the border and 0 inside in the array:")
mat[1:-1, 1:-1] = 0
print(mat)
print("-" * 30)

#Original Matrix:
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]

#6 on the border and 0 inside in the array:
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]
------------------------------


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [4]:
arr = np.empty((8,8), dtype=np.int8)
arr.fill(9)

arr[1::2, ::2] = 3
arr[::2, 1::2] = 3

print("#Checkerboard Pattern: \n" + str(arr) + "\n" + ("-" * 30))

#Checkerboard Pattern: 
[[9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]]
------------------------------


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [5]:
mat1 = np.empty(12).reshape(3,-1)
print(mat1)
print()

mat2 = np.zeros(9, dtype=np.int8).reshape(3, -1)
mat2.fill(6)
print(mat2)

[[5.60806059e-316 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.11519749e+179 1.73740188e-047 3.57822779e-061]
 [4.16074475e-061 9.04294668e-067 1.58848398e-047 1.21026853e-071]]

[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [6]:
temp_fehr_array = np.array([0, 12, 45.21 ,34, 99.91])
temp_centi_array = (temp_fehr_array - 32) * (5/9)
#fehr = centi * (9/5) + 32

print("Values in Fahrenheit degrees:")
print(temp_fehr_array)

print("\nValues in Centigrade degrees:")
print(temp_centi_array)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]

Values in Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.70710678j, 0+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [7]:
complex_arr = np.array([1.00000000+0.70710678j, 0+0.70710678j], dtype=np.complex)

real_part_arr = np.array(complex_arr.real)
imag_part_arr = np.array(complex_arr.imag)

print("#Original array:")
print(complex_arr)

print("\n#Real part array:")
print(real_part_arr)

print("#Imaginary part array:")
print(imag_part_arr)

#Original array:
[1.+0.70710678j 0.+0.70710678j]

#Real part array:
[1. 0.]
#Imaginary part array:
[0.70710678 0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [8]:
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([0, 40])

isfound_bool_arr = np.in1d(arr1, arr2)

print("#Source Array:")
print(arr1)

print("\n#Search-For Array:")
print(arr2)

print("\n#Compare each element of array1 and array2:")
print(isfound_bool_arr)

#Source Array:
[ 0 10 20 40 60]

#Search-For Array:
[ 0 40]

#Compare each element of array1 and array2:
[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [9]:
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])

common_arr = np.intersect1d(arr1, arr2)

print("#First Array:")
print(arr1)

print("\n#Second Array:")
print(arr2)

print("\n#Common elements of array1 and array2:")
print(common_arr)

#First Array:
[ 0 10 20 40 60]

#Second Array:
[10 30 40]

#Common elements of array1 and array2:
[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [10]:
arr = np.array([10, 10, 20, 20, 30, 30])

unique_arr = np.unique(arr)

print("#Original Array:")
print(arr)

print("\n#Unique elements of array:")
print(unique_arr)

#Original Array:
[10 10 20 20 30 30]

#Unique elements of array:
[10 20 30]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [11]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])

xor_arr = np.setxor1d(arr1, arr2)

print("#First Array:")
print(arr1)

print("\n#Second Array:")
print(arr2)

print("\n#eXclusive-OR (XOR) elements of array1 and array2:")
print(xor_arr)

#First Array:
[ 0 10 20 40 60 80]

#Second Array:
[10 30 40 50 70]

#eXclusive-OR (XOR) elements of array1 and array2:
[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [12]:
arr = np.array([1, 2, 5, 8, 3, 0])

assert np.alltrue([1, 2, 5, 8, 3]) == True
assert np.alltrue([1, 2, 5, 8, 3, 0]) == False


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [13]:
arr = np.array([1, 2, 5, 8, 3, 0])

assert np.any([1, 2, 5, 8, 3]) == True
assert np.any([1, 2, 5, 8, 3, 0]) == True
assert np.any([0, 0, 0]) == False
assert np.any([0, 0, 0, 1]) == True
assert np.any([0, 0, 0, -1]) == True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [14]:
arr = np.array([1, 2, 3, 4])

tile2_arr = np.tile(arr, 2)
tile3_arr = np.tile(arr, 3)

print("#Original Array:")
print(arr)

print("\n#Repeating 2 times:")
print(tile2_arr)

print("\n#Repeating 3 times:")
print(tile3_arr)


#Original Array:
[1 2 3 4]

#Repeating 2 times:
[1 2 3 4 1 2 3 4]

#Repeating 3 times:
[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [15]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([11, 22, 3])
arr2d = np.array([[3, 5, 1],[11, 22, 3]], ndmin=2)

#For 1D Array:
assert np.argmax(arr1) == 5 and np.argmin(arr1) == 0
assert np.argmax(arr2) == 1 and np.argmin(arr2) == 2

#For 2D Array:
assert np.unravel_index(np.argmax(arr2d), arr2d.shape) == (1, 1)
assert np.unravel_index(np.argmin(arr2d), arr2d.shape) == (0, 2)
#OR
assert np.unravel_index(arr2d.argmax(), arr2d.shape) == (1, 1)
assert np.unravel_index(arr2d.argmin(), arr2d.shape) == (0, 2)


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [16]:
arr1 = np.array([1, 2])
arr2 = np.array([4, 5])

print("#First Array:")
print(arr1)

print("\n#Second Array:")
print(arr2)

print("\n#Result of arr1 < arr2:")
print(arr1 < arr2)

print("\n#Result of arr1 <= arr2:")
print(arr1 <= arr2)

print("\n#Result of arr1 > arr2:")
print(arr1 > arr2)

print("\n#Result of arr1 >= arr2:")
print(arr1 >= arr2)


#First Array:
[1 2]

#Second Array:
[4 5]

#Result of arr1 < arr2:
[ True  True]

#Result of arr1 <= arr2:
[ True  True]

#Result of arr1 > arr2:
[False False]

#Result of arr1 >= arr2:
[False False]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [17]:
arr = np.array([[2, 8, 4],[1, 9, 3]])

sorted_on_x_axis = np.sort(arr, axis=0) #0: first axis i.e. X axis i.e. 
sorted_on_y_axis = np.sort(arr, axis=1) #1 or -1: second/last axis i.e. Y axis.

print("#Original Array:")
print(arr)

print("\n#Sorted Array on first axis i.e. X-axis means row-wise sorting:")
print(sorted_on_x_axis)

print("\n#Sorted Array on second/last axis i.e. Y-axis means column-wise sorting:")
print(sorted_on_y_axis)


#Original Array:
[[2 8 4]
 [1 9 3]]

#Sorted Array on first axis i.e. X-axis means row-wise sorting:
[[1 8 3]
 [2 9 4]]

#Sorted Array on second/last axis i.e. Y-axis means column-wise sorting:
[[2 4 8]
 [1 3 9]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [18]:
fname_arr = np.array(['Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery'], dtype=np.object)
lname_arr = np.array(['Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum'], dtype=np.object)

sorted_arr = np.lexsort((lname_arr, fname_arr))

print("#First Names Array:")
print(fname_arr)

print("\n#Last Names Array:")
print(lname_arr)

print("\n#Sorted Array w.r.t. (Last Name, First Name) Tuples:")
print(sorted_arr)

#First Names Array:
['Betsey' 'Shelley' 'Lanell' 'Genesis' 'Margery']

#Last Names Array:
['Battle' 'Brien' 'Plotner' 'Stahl' 'Woolum']

#Sorted Array w.r.t. (Last Name, First Name) Tuples:
[0 3 2 4 1]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [19]:
arr2d = np.array([[0, 10, 20], [20, 30, 40]])
gt_number = 10

matched_arr = arr2d[arr2d > 10]

idx_tuple = np.nonzero(arr2d > 10)
row1_idx_arr, row2_idx_arr = idx_tuple[0], idx_tuple[1]

print("#Original Array:")
print(arr2d)

print("\n#Array with elements > 10:")
print(matched_arr)

print("\n#Their (x,y) indices are:")
print([x_y for x_y in zip(row1_idx_arr, row2_idx_arr)])


#Original Array:
[[ 0 10 20]
 [20 30 40]]

#Array with elements > 10:
[20 20 30 40]

#Their (x,y) indices are:
[(0, 2), (1, 0), (1, 1), (1, 2)]


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [20]:
arr_6_f32 = np.empty((2,3), dtype=np.float32)
arr_5_f64 = np.empty(5, dtype=np.float64)
arr_3_i16 = np.empty(3, dtype=np.int16)
arr_4_i8 = np.empty(4, dtype=np.int8)
arr_2_i64 = np.empty(2, dtype=np.int64)
arr_5_bool = np.empty(5, dtype=np.bool)
arr_1_complex = np.empty(1, dtype=np.complex)

arr_list = [arr_6_f32, arr_5_f64, arr_3_i16, arr_4_i8, arr_2_i64, arr_5_bool, arr_1_complex]

output_string_template = "\n#Array(size:{}, type:{}) consumes {} bytes of memory."

for arr in arr_list:
    arr = np.array(arr)
    print(output_string_template.format(arr.size, arr.dtype, (arr.size * arr.itemsize)))



#Array(size:6, type:float32) consumes 24 bytes of memory.

#Array(size:5, type:float64) consumes 40 bytes of memory.

#Array(size:3, type:int16) consumes 6 bytes of memory.

#Array(size:4, type:int8) consumes 4 bytes of memory.

#Array(size:2, type:int64) consumes 16 bytes of memory.

#Array(size:5, type:bool) consumes 5 bytes of memory.

#Array(size:1, type:complex128) consumes 16 bytes of memory.


## Great Job!